### ISSUE TITLE
 No such file or directory: '../kbp_data/label2id.dat'

### ISSUE THREAD

**Issue by SeekPoint** [sanmusunrise/NPNs#2]
ub16hp@UB16HP:~/ub16_prj/NPNs/src$ python NPN_TS.py kbp_config.cfg
2018-12-04 20:07:50.388605: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-04 20:07:50.449166: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-04 20:07:50.449441: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 147.38MiB
2018-12-04 20:07:50.449465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "NPN_TS.py", line 416, in <module>
    model.load_data_and_embedding()
  File "NPN_TS.py", line 387, in load_data_and_embedding
    self.train_data = EEData("train", self.configure)
  File "/home/ub16hp/ub16_prj/NPNs/src/EEData.py", line 42, in __init__
    self.load(split)
  File "/home/ub16hp/ub16_prj/NPNs/src/EEData.py", line 229, in load
    self.load_label2id(label2id_file)
  File "/home/ub16hp/ub16_prj/NPNs/src/EEData.py", line 244, in load_label2id
    for line in open(file_name):
IOError: [Errno 2] No such file or directory: '../kbp_data/label2id.dat'

**Comment by sanmusunrise** [comment]
Hi,
    Please carefully read the README file and send me an email to request for the datasets if you have the license.

Best,
Hongyu Lin

**Comment by SeekPoint** [comment]
license? i haven't  ;(
